import type { SkillGroup } from "./types";

export const skillGroups: SkillGroup[] = [
  {
    title: "AI & LLM systems",
    description: "Retrieval, agents and real-time voice",
    skills: [
      "RAG",
      "Chunking & embeddings",
      "Hybrid retrieval",
      "Tool calling",
      "MCP",
      "Prompt engineering",
      "STT / TTS",
      "Pipecat",
      "Gemini",
      "Claude",
      "OpenAI SDK",
      "OpenRouter",
      "ElevenLabs",
      "Vapi",
    ],
  },
  {
    title: "Backend",
    description: "APIs, streaming and services",
    skills: [
      "Python",
      "FastAPI",
      "Pydantic",
      "SQLAlchemy",
      "Node.js",
      "Express",
      "REST APIs",
      "WebSockets",
      "Server-Sent Events",
      "Pusher",
    ],
  },
  {
    title: "Frontend",
    description: "Product interfaces",
    skills: [
      "TypeScript",
      "React",
      "Next.js",
      "JavaScript",
      "Tailwind CSS",
      "shadcn/ui",
      "Redux Toolkit",
      "Zustand",
      "React Native (Expo)",
      "SASS",
      "Styled Components",
    ],
  },
  {
    title: "Data",
    description: "Storage, vectors and pipelines",
    skills: [
      "PostgreSQL",
      "pgvector",
      "Supabase",
      "Prisma",
      "MongoDB",
      "Web data extraction",
      "Data validation",
    ],
  },
  {
    title: "Tooling",
    description: "Delivery and testing",
    skills: [
      "Git & GitHub",
      "GitHub Actions",
      "Docker",
      "Vercel",
      "pytest",
      "Vitest",
      "Playwright",
    ],
  },
];
